### ISSUE TITLE
Registration won't work

### ISSUE THREAD

**Issue by dhofstetter** [n1te1337/apigility-blog-example#1]
If i perform a post Request with Content-Type: application/json to my http://example.domain.com/auth/registration

I always get this error:

<pre>{
       "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
       "title": "Internal Server Error",
       "status": 500,
       "detail": "Listed input filter "Auth\V1\Rest\Registration\Validator" does not exist; cannot validate request"
}
</pre>

The inputfilter won't exist I understand so far. But it is not included in git clone. What have I done wrong?

I get the project running with inserting my own db credentials, and executing:
./composer.phar install
after that I simply started with:
php -S 0.0.0.0:8888 -t public public/index.php

Best regards Daniel

**Comment by n1te1337** [comment]
@dhofstetter sorry for the late reply, I don't seem to be getting notifications from Github :confused: 

I've updated the code, the issue was caused by the breaking changes in `input_filter` added in Apigility v1.0.0.

Please let me know if this fixes your problem.

**Comment by dhofstetter** [comment]
Thank you for fixing it, i was just recreating all fields in apigility and then I was able to see that the config files changes a bit ;) which lead me to the solution. I'm sorry that I havent said anything that I found the issue. But I also simply forgot that I asked you about that ;)

Br Daniel

**Comment by tasmaniski** [comment]
I have a fresh installation, when I try to register i got an error:

{
    type: "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html"
    title: "Bad Request"
    status: 400
    detail: "JSON decoding error: Syntax error, malformed JSON"
}

Admin part works properly, I can see that rest "register" is created. 
Any thoughts?

**Comment by dhofstetter** [comment]
Can you give more detailed informations about your request? How do you perform the request, can you show us the payload? 

Can you see the fields neccessary for register in the admin interface?

**Comment by tasmaniski** [comment]
I sent a POST request with header Content-Type "application/json" and params
username=tasmaniski@gmail.com&password=testpass&firstname=Alexandar&lastname=Manicicici

Check screen shot please.

![ss](https://cloud.githubusercontent.com/assets/2909695/3166915/5f0946e2-eb66-11e3-94b9-223f9c480c25.png)

**Comment by n1te1337** [comment]
@tasmaniski you're passing form values instead of json. Go to the "Raw" tab in the RestClient and paste:

``` javascript
{
  "username": "tasmaniski@gmail.com",
  "password": "testpass",
  "firstname": "Alexandar",
  "lastname": "Manicicici"
}
```

You should also add a header for Content-Type of `application/json` if you haven't already done so.

**Comment by tasmaniski** [comment]
Yap, thanks, I miss that :/ 

There is one error on missing service. In Auth\V1\Rest\Registration\RegistrationResource 

```
public function getRegistrationService(){
    return $this->getServiceManager()->get('Auth\V1\RegistrationService');
}
```

but there is no Auth\V1\RegistrationService in config file. 

Adding this to end of modul Auth's config solve the error:

```
'service_manager' => array(
        'invokables' => array(
            'Auth\V1\RegistrationService'        => 'Auth\V1\Rest\Registration\RegistrationService'
        ),
),
```

**Comment by n1te1337** [comment]
Thanks I just fixed it, I must've deleted it when I was updating the code to work with 1.0.0
