### ISSUE TITLE
403 :(

### ISSUE THREAD

**Issue by kukoman** [n1te1337/apigility-blog-example#4]
Hi there,

I'm really despaired and looking for solution

I created latest (dev-master) apigility/zf project also tried with this blog example but I always end up with 403 when trying to access user resource

my steps (except correctly configuring database and configs):

POST: http://test2.lc/auth/registration

``` json
{
  "username": "n1teleet@gmail.com",
  "password": "testpass",
  "firstname": "Pav",
  "lastname": "Zwierzynski"
}
```

response:

``` json
{
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
    "title": "Success",
    "status": 200,
    "detail": "The entity has been created"
}
```

POST: http://test2.lc/auth/login

``` json
{
  "username": "n1teleet@gmail.com",
  "password": "testpass",
  "grant_type": "password",
  "client_id": "webapp"
}
```

response:

``` json
{
    "access_token": "30f03a9d46cd3698bb0ffd091fbb37fe3557fae8",
    "expires_in": 3600,
    "token_type": "Bearer",
    "scope": null,
    "refresh_token": "6dc6166d948072962c0a8142b1f5162bafadcf36"
}
```

POST: http://test2.lc/post
(header Authorization: Bearer 53f382dfbb9fa27f12e268de7a02c8b7613a67bc)

``` json
{
  "postTitle": "Sample post",
  "postBody": "This is just a sample post to see if the API works"
}
```

response:

``` json
{
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
    "title": "Forbidden",
    "status": 403,
    "detail": "Forbidden"
}
```

**if anyone can help I'm inviting for 10 beers!**

**Comment by remiq** [comment]
> "access_token": "30f03a9d46cd3698bb0ffd091fbb37fe3557fae8",
> (header Authorization: Bearer 53f382dfbb9fa27f12e268de7a02c8b7613a67bc)

POST /post request should have access token in Authorization header. In this example:
Authorization: Bearer 30f03a9d46cd3698bb0ffd091fbb37fe3557fae8

**Comment by kukoman** [comment]
Thank for your time, somehow I deleted vendor folder, updated all packages and it worked.
![Cheers](http://beerisbread.com/wp-content/uploads/2014/06/tumblr_n7twr5sK481tf884wo2_1280.jpg)
